import { MigrationInterface, QueryRunner } from "typeorm";

export class InitPostgresSchema1749175500822 implements MigrationInterface {
    name = 'InitPostgresSchema1749175500822'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "entity" DROP CONSTRAINT "entity_sys_entity_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff_service" DROP CONSTRAINT "fk_service"`);
        await queryRunner.query(`ALTER TABLE "class" DROP CONSTRAINT "service_business_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" DROP CONSTRAINT "fk_business_working_hour_sys_day"`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" DROP CONSTRAINT "fk_business_working_hour_business"`);
        await queryRunner.query(`DROP INDEX "public"."fki_sys_data_type_data_type_id_fk"`);
        await queryRunner.query(`ALTER TABLE "service" DROP CONSTRAINT "duration_greate_0"`);
        await queryRunner.query(`ALTER TABLE "service" DROP CONSTRAINT "buffer_time_greate_0"`);
        await queryRunner.query(`ALTER TABLE "class" DROP CONSTRAINT "buffer_time_greate_0"`);
        await queryRunner.query(`ALTER TABLE "class" DROP CONSTRAINT "duration_greate_0"`);
        await queryRunner.query(`ALTER TABLE "sys_data_by_language" DROP CONSTRAINT "sys_data_by_language_data_type_id_language_id_sys_data_id_key"`);
        await queryRunner.query(`ALTER TABLE "staff_service" DROP CONSTRAINT "staff_service_entity_id_service_id_key"`);
        await queryRunner.query(`CREATE TABLE "report" ("id" SERIAL NOT NULL, "approved" boolean NOT NULL DEFAULT false, "price" integer NOT NULL, "make" character varying NOT NULL, "model" character varying NOT NULL, "year" integer NOT NULL, "lng" integer NOT NULL, "lat" integer NOT NULL, "mileage" integer NOT NULL, "userId" integer, CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "admin" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD CONSTRAINT "PK_09582baa74eeb95fd5f54e8a44e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "sys_state" DROP CONSTRAINT "state_country_id_fkey"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "sys_country_id_seq" OWNED BY "sys_country"."id"`);
        await queryRunner.query(`ALTER TABLE "sys_country" ALTER COLUMN "id" SET DEFAULT nextval('"sys_country_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "sys_country" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "sys_state_id_seq" OWNED BY "sys_state"."id"`);
        await queryRunner.query(`ALTER TABLE "sys_state" ALTER COLUMN "id" SET DEFAULT nextval('"sys_state_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "sys_state" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sys_industry" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sys_data_by_language" DROP CONSTRAINT "sys_data_by_language_language_id_fkey"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "sys_language_id_seq" OWNED BY "sys_language"."id"`);
        await queryRunner.query(`ALTER TABLE "sys_language" ALTER COLUMN "id" SET DEFAULT nextval('"sys_language_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "business_calendar_colors" DROP CONSTRAINT "business_calendar_colors_sys_color_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sys_color_types" DROP CONSTRAINT "csys_color_types_pkey"`);
        await queryRunner.query(`ALTER TABLE "sys_color_types" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "sys_color_types" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sys_color_types" ADD CONSTRAINT "sys_color_types_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "contact_detail" DROP CONSTRAINT "contact_detail_sys_contact_detail_type_id_fkey"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "sys_contact_detail_type_id_seq" OWNED BY "sys_contact_detail_type"."id"`);
        await queryRunner.query(`ALTER TABLE "sys_contact_detail_type" ALTER COLUMN "id" SET DEFAULT nextval('"sys_contact_detail_type_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "sys_contact_detail_type" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "business" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "business" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "entity" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "entity" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "entity" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."idx_entity_full_name"`);
        await queryRunner.query(`ALTER TABLE "entity" DROP COLUMN "full_name"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","full_name","defaultdb","public","entity"]);
        await queryRunner.query(`ALTER TABLE "entity" ADD "full_name" text GENERATED ALWAYS AS (TRIM(BOTH FROM ((first_name || ' ') || last_name))) STORED NOT NULL`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["defaultdb","public","entity","GENERATED_COLUMN","full_name","TRIM(BOTH FROM ((first_name || ' ') || last_name))"]);
        await queryRunner.query(`ALTER TABLE "staff_working_hour" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "staff_working_hour" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "staff_working_hour" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "staff_working_hour" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "service" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "service" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "staff_service" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff_service" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "contact_detail" ALTER COLUMN "is_primary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "class" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "class" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "class" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "class" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP CONSTRAINT "business_language_unique_key"`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP COLUMN "business_id"`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD "business_id" integer`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP COLUMN "language_id"`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD "language_id" integer`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "booked_class" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "booked_class" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "UQ_6ca108494f16c80b10df01db467" UNIQUE ("booking_number")`);
        await queryRunner.query(`CREATE INDEX "idx_entity_full_name" ON "entity" ("full_name") `);
        await queryRunner.query(`ALTER TABLE "sys_data_by_language" ADD CONSTRAINT "UQ_892d9ca4f88a2b001842f0278e5" UNIQUE ("data_type_id", "language_id", "sys_data_id")`);
        await queryRunner.query(`ALTER TABLE "staff_service" ADD CONSTRAINT "UQ_b14241fee47f925014702f47993" UNIQUE ("entity_id", "service_id")`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD CONSTRAINT "business_language_unique_key" UNIQUE ("business_id", "language_id")`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_e347c56b008c2057c9887e230aa" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_state" ADD CONSTRAINT "state_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "sys_country"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_data_by_language" ADD CONSTRAINT "sys_data_by_language_language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "sys_language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entity" ADD CONSTRAINT "entity_sys_entity_type_id_fkey" FOREIGN KEY ("sys_entity_type_id") REFERENCES "sys_entity_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_service" ADD CONSTRAINT "staff_service_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "role_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_detail" ADD CONSTRAINT "contact_detail_sys_contact_detail_type_id_fkey" FOREIGN KEY ("sys_contact_detail_type_id") REFERENCES "sys_contact_detail_type"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class" ADD CONSTRAINT "class_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD CONSTRAINT "FK_ff37f50b60d9e06aabb449433fe" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD CONSTRAINT "FK_cdf57c250288b1a54a884b12e4b" FOREIGN KEY ("language_id") REFERENCES "sys_language"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_calendar_colors" ADD CONSTRAINT "business_calendar_colors_sys_color_type_id_fkey" FOREIGN KEY ("sys_color_type_id") REFERENCES "sys_color_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" ADD CONSTRAINT "business_working_hour_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" ADD CONSTRAINT "business_working_hour_sys_day_id_fkey" FOREIGN KEY ("sys_day_id") REFERENCES "sys_day"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "business_working_hour" DROP CONSTRAINT "business_working_hour_sys_day_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" DROP CONSTRAINT "business_working_hour_business_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "business_calendar_colors" DROP CONSTRAINT "business_calendar_colors_sys_color_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP CONSTRAINT "FK_cdf57c250288b1a54a884b12e4b"`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP CONSTRAINT "FK_ff37f50b60d9e06aabb449433fe"`);
        await queryRunner.query(`ALTER TABLE "class" DROP CONSTRAINT "class_business_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "contact_detail" DROP CONSTRAINT "contact_detail_sys_contact_detail_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "role_business_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff_service" DROP CONSTRAINT "staff_service_service_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "entity" DROP CONSTRAINT "entity_sys_entity_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sys_data_by_language" DROP CONSTRAINT "sys_data_by_language_language_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sys_state" DROP CONSTRAINT "state_country_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_e347c56b008c2057c9887e230aa"`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP CONSTRAINT "business_language_unique_key"`);
        await queryRunner.query(`ALTER TABLE "staff_service" DROP CONSTRAINT "UQ_b14241fee47f925014702f47993"`);
        await queryRunner.query(`ALTER TABLE "sys_data_by_language" DROP CONSTRAINT "UQ_892d9ca4f88a2b001842f0278e5"`);
        await queryRunner.query(`DROP INDEX "public"."idx_entity_full_name"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "UQ_6ca108494f16c80b10df01db467"`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "booked_class" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "booked_class" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" ADD "updated_at" date`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" ADD "created_at" date NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP COLUMN "language_id"`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD "language_id" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP COLUMN "business_id"`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD "business_id" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business_language" ADD CONSTRAINT "business_language_unique_key" UNIQUE ("business_id", "language_id")`);
        await queryRunner.query(`ALTER TABLE "class" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "class" ADD "updated_at" date DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "class" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "class" ADD "created_at" date NOT NULL DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "contact_detail" ALTER COLUMN "is_primary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff_service" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "staff_service" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "service" ADD "updated_at" date DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "service" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "service" ADD "created_at" date NOT NULL DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "staff_working_hour" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "staff_working_hour" ADD "updated_at" date`);
        await queryRunner.query(`ALTER TABLE "staff_working_hour" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "staff_working_hour" ADD "created_at" date NOT NULL DEFAULT now()`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","full_name","defaultdb","public","entity"]);
        await queryRunner.query(`ALTER TABLE "entity" DROP COLUMN "full_name"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["defaultdb","public","entity","GENERATED_COLUMN","full_name",""]);
        await queryRunner.query(`ALTER TABLE "entity" ADD "full_name" text`);
        await queryRunner.query(`CREATE INDEX "idx_entity_full_name" ON "entity" ("full_name") `);
        await queryRunner.query(`ALTER TABLE "entity" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "entity" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "entity" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "business" ADD "updated_at" date DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "business" ADD "created_at" date NOT NULL DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "sys_contact_detail_type" ALTER COLUMN "id" SET DEFAULT nextval('sys_contact_type_id_seq')`);
        await queryRunner.query(`ALTER TABLE "sys_contact_detail_type" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "sys_contact_detail_type_id_seq"`);
        await queryRunner.query(`ALTER TABLE "contact_detail" ADD CONSTRAINT "contact_detail_sys_contact_detail_type_id_fkey" FOREIGN KEY ("sys_contact_detail_type_id") REFERENCES "sys_contact_detail_type"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_color_types" DROP CONSTRAINT "sys_color_types_pkey"`);
        await queryRunner.query(`ALTER TABLE "sys_color_types" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "sys_color_types" ADD "id" smallint NOT NULL DEFAULT nextval('csys_color_types_id_seq')`);
        await queryRunner.query(`ALTER TABLE "sys_color_types" ADD CONSTRAINT "csys_color_types_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "business_calendar_colors" ADD CONSTRAINT "business_calendar_colors_sys_color_type_id_fkey" FOREIGN KEY ("sys_color_type_id") REFERENCES "sys_color_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_language" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "sys_language_id_seq"`);
        await queryRunner.query(`ALTER TABLE "sys_data_by_language" ADD CONSTRAINT "sys_data_by_language_language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "sys_language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_industry" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sys_state" ALTER COLUMN "id" SET DEFAULT nextval('state_id_seq')`);
        await queryRunner.query(`ALTER TABLE "sys_state" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "sys_state_id_seq"`);
        await queryRunner.query(`ALTER TABLE "sys_country" ALTER COLUMN "id" SET DEFAULT nextval('country_id_seq')`);
        await queryRunner.query(`ALTER TABLE "sys_country" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "sys_country_id_seq"`);
        await queryRunner.query(`ALTER TABLE "sys_state" ADD CONSTRAINT "state_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "sys_country"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP CONSTRAINT "PK_09582baa74eeb95fd5f54e8a44e"`);
        await queryRunner.query(`ALTER TABLE "business_language" DROP COLUMN "id"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "report"`);
        await queryRunner.query(`ALTER TABLE "staff_service" ADD CONSTRAINT "staff_service_entity_id_service_id_key" UNIQUE ("entity_id", "service_id")`);
        await queryRunner.query(`ALTER TABLE "sys_data_by_language" ADD CONSTRAINT "sys_data_by_language_data_type_id_language_id_sys_data_id_key" UNIQUE ("data_type_id", "language_id", "sys_data_id")`);
        await queryRunner.query(`ALTER TABLE "class" ADD CONSTRAINT "duration_greate_0" CHECK ((default_duration_in_minutes >= 0))`);
        await queryRunner.query(`ALTER TABLE "class" ADD CONSTRAINT "buffer_time_greate_0" CHECK ((default_buffer_time_in_minutes >= 0))`);
        await queryRunner.query(`ALTER TABLE "service" ADD CONSTRAINT "buffer_time_greate_0" CHECK ((default_buffer_time_in_minutes >= 0))`);
        await queryRunner.query(`ALTER TABLE "service" ADD CONSTRAINT "duration_greate_0" CHECK ((default_duration_in_minutes >= 0))`);
        await queryRunner.query(`CREATE INDEX "fki_sys_data_type_data_type_id_fk" ON "sys_data_by_language" ("data_type_id") `);
        await queryRunner.query(`ALTER TABLE "business_working_hour" ADD CONSTRAINT "fk_business_working_hour_business" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_working_hour" ADD CONSTRAINT "fk_business_working_hour_sys_day" FOREIGN KEY ("sys_day_id") REFERENCES "sys_day"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class" ADD CONSTRAINT "service_business_id_fkey" FOREIGN KEY ("business_id", "business_id") REFERENCES "business"("id","id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_service" ADD CONSTRAINT "fk_service" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entity" ADD CONSTRAINT "entity_sys_entity_type_id_fkey" FOREIGN KEY ("sys_entity_type_id") REFERENCES "sys_entity_type"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
