## Login
@baseUrl = http://localhost:3000/api/
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTc1MDM4MDM3NiwiZXhwIjoxNzUwNTUzMTc2fQ.8B9nSsvwItXqgf6qD6mr85hFNhTaNte_y2Y0_Zc0qvY


@cookie=refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImZ1bGxfbmFtZSI6Ikd1cmdlbiBDaGxpbmdhcnlhbiIsImVtYWlsIjoiY2hsaW5nYXJpYW4uZ0BnbWFpbC5jb20iLCJyZWZyZXNoIjp0cnVlLCJidXNpbmVzc19pZCI6NTAsImlhdCI6MTc1MDUyMTgzMSwiZXhwIjoxNzUxMTI2NjMxfQ.y8_U6cUQQuAjlfw9VJkv9XzT7vV6h9axSUJzbooRkq0; Max-Age=604800; Path=/; Expires=Sat, 28 Jun 2025 16:03:51 GMT; HttpOnly; Secure,XSRF-TOKEN=ed6da89e2914eccc3e1b45bbe54c2a483582c0cdad724c3867fc64b1d86ebdc4; Path=/; Secure
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImZ1bGxfbmFtZSI6Ikd1cmdlbiBDaGxpbmdhcnlhbiIsImVtYWlsIjoiY2hsaW5nYXJpYW4uZ0BnbWFpbC5jb20iLCJyZWZyZXNoIjp0cnVlLCJidXNpbmVzc19pZCI6NTAsImlhdCI6MTc1MDUyMTgzMSwiZXhwIjoxNzUwNjk0NjMxfQ.HmCTj54xYkX1MOEIf1a9kRAHZ2B2JKqSm5jRMKJWmFk

### login

POST {{baseUrl}}auth/login
content-type: application/json

{
    "email": "chlingarian.g@gmail.com",
    "password": "000"
}

### VerifyCode

POST {{baseUrl}}auth/email-verify
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTc1MDUyMTUxMSwiZXhwIjoxNzUwNjk0MzExfQ.Y3jJsGtLwV31Irdmhct1nAqdXr_w3_j-VZY6laiNqgw

{
    "code": "GCSZEV"
}

### Login

PUT {{baseUrl}}/account/staff/12
Vary: Origin
Access-Control-Allow-Credentials: true
Set-Cookie: {{cookie}}
Content-Type: application/json; charset=utf-8
Authorization: Bearer: {{token}}

{
    "first_name": "Gurgen"
}

###

PUT {{baseUrl}}/account/forgotPassword
Vary: Origin
Access-Control-Allow-Credentials: true
Set-Cookie: {{cookie}}
Content-Type: application/json; charset=utf-8
Authorization: Bearer: {{token}}

{
    "email": "gug.chilo@gmail.com",
    "newPassword": "000",
    "confirmPassword": "000"
}

###

PUT {{baseUrl}}/account/resetPassword
Vary: Origin
Access-Control-Allow-Credentials: true
Set-Cookie: {{cookie}}
Content-Type: application/json; charset=utf-8
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODAsImlhdCI6MTc1MDM4MTc4MSwiZXhwIjoxNzUwNTU0NTgxfQ.gso0kK8Mn8WYRb6a3Zl6qnVDIuxCNDvpdLesx4mu4Ew

{
    "email": "gug.chilo@gmail.com",
    "newPassword": "000",
    "confirmPassword": "000"
}

###

POST {{baseUrl}}/account/refresh-token
Vary: Origin
Access-Control-Allow-Credentials: true
Cookie: {{cookie}}
Content-Type: application/json; charset=utf-8
Authorization: Bearer: {{token}}

{
    "email": "gug.chilo@gmail.com",
    "newPassword": "000",
    "confirmPassword": "000"
}

###

POST {{baseUrl}}/api/customer/search
Vary: Origin
Access-Control-Allow-Credentials: true
Cookie: {{cookie}}
Content-Type: application/json; charset=utf-8
Authorization: Bearer: {{token}}

{
    "pattern": "reg"
}

### preferences

GET {{baseUrl}}/api/account-preference
Vary: Origin
Access-Control-Allow-Credentials: true
Cookie: {{cookie}}
Content-Type: application/json; charset=utf-8
Authorization: Bearer: {{token}}

{
    "key": "work_week",
    "value": "false"
}

### register business

POST {{baseUrl}}/api/business-account/register/owner
Content-Type: application/json; charset=utf-8

{
    "email": "gug.chitdgt@gmail.com",
    "password": "000000",
    "first_name": "string",
    "last_name": "string"
}

### resend email

POST {{baseUrl}}/api/business-account/register/email/resend
Content-Type: application/json; charset=utf-8
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMxLCJpYXQiOjE3NTAzODk5MzEsImV4cCI6MTc1MDU2MjczMX0.UZWZsjdiGwMNRj2g4k4AdlmcqNQzMhvFJK2DpdclveM

{
    "email": "gug.chitt@gmail.com",
    "password": "000000",
    "first_name": "string",
    "last_name": "string"
}